import jsPDF from "jspdf";
import { COLORS } from "./colors";

export function addFooter(doc: jsPDF) {
  const totalPages = doc.getNumberOfPages();

  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);

    doc.setDrawColor(
      COLORS.primary.r,
      COLORS.primary.g,
      COLORS.primary.b
    );

    doc.line(15, 285, 195, 285);

    doc.setFontSize(10);

    doc.setTextColor(
      COLORS.gray.r,
      COLORS.gray.g,
      COLORS.gray.b
    );

    doc.text(
      "Generated by AI Career Copilot",
      15,
      291
    );

    doc.text(
      `Page ${i} of ${totalPages}`,
      170,
      291
    );
  }

  doc.setTextColor(
    COLORS.black.r,
    COLORS.black.g,
    COLORS.black.b
  );
}