import { FaLightbulb, FaRobot } from "react-icons/fa";
import Card from "../Common/Card";
import SectionTitle from "../Common/SectionTitle";

interface SuggestionsCardProps {
  suggestions: string[];
}

function SuggestionsCard({
  suggestions,
}: SuggestionsCardProps) {
  return (
    <Card>

      <div className="flex items-center justify-between mb-6">

        <SectionTitle title="🤖 AI Recommendations" />

        <div className="rounded-full bg-yellow-500/15 px-4 py-2 text-sm font-bold text-yellow-300">
          {suggestions.length}{" "}
          {suggestions.length === 1
            ? "Suggestion"
            : "Suggestions"}
        </div>

      </div>

      {suggestions.length === 0 ? (

        <div className="rounded-2xl border border-dashed border-slate-700 bg-slate-800/40 p-8 text-center">

          <p className="text-lg text-slate-400">
            No recommendations available.
          </p>

        </div>

      ) : (

        <div className="space-y-5">

          {suggestions.map((suggestion, index) => (

            <div
              key={index}
              className="flex gap-5 rounded-2xl border border-yellow-500/10 bg-yellow-500/5 p-5 transition-all duration-300 hover:bg-yellow-500/10 hover:translate-x-1"
            >

              {/* Number */}

              <div className="flex h-10 w-10 flex-shrink-0 items-center justify-center rounded-full bg-yellow-500 text-lg font-bold text-slate-900">
                {index + 1}
              </div>

              {/* Content */}

              <div>

                <div className="mb-2 flex items-center gap-2">

                  <FaLightbulb className="text-yellow-400" />

                  <span className="font-semibold text-yellow-300">
                    Recommendation {index + 1}
                  </span>

                </div>

                <p className="leading-7 text-slate-200">
                  {suggestion}
                </p>

              </div>

            </div>

          ))}

        </div>

      )}

      <div className="mt-8 rounded-2xl border border-cyan-500/10 bg-cyan-500/5 p-6">

        <div className="mb-3 flex items-center gap-3">

          <FaRobot className="text-2xl text-cyan-400" />

          <h3 className="text-lg font-bold text-cyan-300">
            AI Career Copilot Advice
          </h3>

        </div>

        <p className="leading-7 text-slate-300">
          These recommendations are generated by AI after analyzing your
          resume, skills, ATS compatibility, and section quality.
          Applying these improvements can strengthen your resume and
          increase your chances of getting shortlisted by recruiters.
        </p>

      </div>

    </Card>
  );
}

export default SuggestionsCard;